version: "3.5"

volumes:
  db-data:
    name: db-data

networks:
  web:
    name: web
  fk:
    name: fk
    ipam:
      config:
        - subnet: 161.80.0.0/16

services:
  db:
    image: mariadb:10.4
    container_name: db-data
    restart: unless-stopped
    ports:
      - "5506:3306"
    command: --max-connections=500 --max-allowed-packet=200M
    env_file:
      - database.env
    volumes:
      - ./database-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/mysql
    networks:
      web:
      fk:
        ipv4_address: 161.80.0.17
  fk-server:
    image: sourcestuff:imagetag
    entrypoint: [ "/bin/bash", "/app/bin/dist", "-Dconfig.file=/app/bin/application.conf", "-Dlogger.file=/app/bin/logback.xml", "-J-Xms4608M", "-J-Xmx6144M", "-J-Xss1M"]
    container_name: fk-server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      "4000:9000"
    networks:
      web:
      fk:
        ipv4_address: 161.80.0.14
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:9000 || exit 1
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 1m
